### ISSUE TITLE
Convert to .NET Core

### ISSUE THREAD

**Issue by iblazhko** [DanielBMarkham/easyam#1]
To make the tool accessible to a broader audience (macOS, Linux), would be nice to convert it to .NET Core.

I tried to move all the source files into a .NET Core project, all code except one function compiles, and most of the tests pass.

The problematic function is `getFakeFileInfo` that uses `System.CodeDom.Compiler.TempFileCollection` (not available in .NET Core). But this can be replaced with `System.IO.Path.GetTempFileName`.

Some tests are still failing, e.g.

- `EAT_TAIL`
- some tests in `ROUNDTRIP` group

Not sure if this a result of the conversion to .NET Core or my environment is different.

You can see the conversion draft at https://github.com/iblazhko/easyam-core/

**Comment by DanielBMarkham** [comment]
In-progress with the app rewrite.

https://wiki.info-ops.org/index.php/EasyAM#Version_2
