### ISSUE TITLE
Dogfooding

### ISSUE THREAD

**Issue by iblazhko** [DanielBMarkham/easyam#3]
Proposal: Document EasyAM tool using EasyAM language

Having EasyAM tool documented using the EasyAM language itself would be a great way of demonstrating EasyAM usage in practice.

**Comment by DanielBMarkham** [comment]
Great idea.

I'm abandoning this repo in favor of a rewrite. (I'm leaving this here as-is for readers of the book who want to view/use the code the way it was when the book was written)

This will include dog-fooding (of course!)

https://wiki.info-ops.org/index.php/EasyAM#Version_2
